#!/bin/sh

# Name: noskype
#
# Block access to skype via ebtable rules

# Block /24 address ranges where Skype Servers for login are located.
# To block only servers remove "| sed 's#\.[0-9]*$#.0/24#'" in the for loop.
 

for dest in `for i in $(seq 0 16) ; do nslookup dsn${i}.d.skype.net 8.8.8.8 ; done | grep '^Address' | grep -v '8.8.8.8' | sed 's#.* ##' | grep '^[1-9]' | sed 's#\.[0-9]*$#.0/24#' | sort -u`
do
	ebtables  -I FORWARD --out-interface client0 --protocol IPv4 --ip-source $dest -j DROP
done

